spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/battle_service_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: create
logging:
  level:
    root: info
server:
  port: 8080
battlefield:
  width: 20
  length: 50
gun-service-server:
  host: localhost
  port: 8081
