spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: info
server:
  port: 8082
battlefield:
  width: 20
  length: 50
gun-service-server:
  host: localhost
  port: 8081
enemy-service-server:
  host: localhost
  port: 8085
